networks:
  mynet:
    external: true  # your Mongo container is already on this network

services:
  app:
    build: .
    image: donocounter:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - mynet

    environment:
      NODE_ENV: production
      PORT: "3000"
      MONGO_URL: ${MONGO_URL}
      DONATION_WEBHOOK_KEY: ${DONATION_WEBHOOK_KEY}

    healthcheck:
      test: ["CMD", "node", "dist/src/healthcheck.js"]
      interval: 30s
      timeout: 5s
      retries: 3
